name: symfony
base: core20
version:
  - 5.5.1
summary: The Symfony CLI tool
description: |
  The Symfony binary to develop Symfony applications.
grade: devel
confinement: strict
contact: contact@jeremyfaton.me
website: https://www.jeremyfaton.me
architectures:
  - build-on: s390x
  - build-on: ppc64el
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64
  - build-on: i386
parts:
  symfony:
    plugin: go
    source-type: git
    source: https://github.com/symfony-cli/symfony-cli
apps:
  symfony:
    command: bin/symfony-cli
